@baseURL = http://localhost:4000/api/logins
# Teste de cadastro de usuário
POST {{baseURL}}/cadastro
Content-Type: application/json

{
    "nome": "Nome do Usuário",
    "email": "nome@email.com",
    "senha": "senha123"
}
###
# Teste de login
POST {{baseURL}}/
Content-Type: application/json

{
    "email": "nome@email.com",
    "senha": "senha123"
}